### ISSUE TITLE
Fix weird broken nav thing

### ISSUE THREAD

**Issue by tati** [thenextbilliononline/thenextbillion.online#1]

**Comment by tati** [comment]
fixed with https://github.com/thenextbilliononline/thenextbillion.online/pull/9 lolz

**Comment by simplymathematics** [comment]
Not seeing this fix. Did you push to master?

**Comment by tati** [comment]
![screen shot 2017-04-26 at 12 28 11 pm](https://cloud.githubusercontent.com/assets/12241872/25445241/e24322d8-2a7b-11e7-9473-18eac32ccaa3.png)

Looks good to me? This wasn't a design PR was just to fix the weird bug where there was a gray bar above the nav @meyerscr

**Comment by simplymathematics** [comment]
thenextbillion.online/#resources doesn't scroll down to the #resources section

**Comment by tati** [comment]
fixed with https://github.com/thenextbilliononline/thenextbillion.online/pull/14
