### ISSUE TITLE
Swap background photos

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#11]
Should be one of the sunset ones, not the sandstorm ones. This color scheme is pretty bad.

**Comment by simplymathematics** [comment]
New Background image is here: https://drive.google.com/open?id=0B6rdz5e2akDGZGxxSjVxemJqN1k

**Comment by tati** [comment]
swapped for now still not sure if the gradient I put on it is perf yet

https://github.com/thenextbilliononline/thenextbillion.online/pull/16

**Comment by simplymathematics** [comment]
I kinda hate the gradient. If you need a different color scheme for the photo, I can reshoot it.

**Comment by simplymathematics** [comment]
@Christianhendricks has made a beautiful theme with the sandstorm pics and will be building a pallette as mentioned in #47

**Comment by tati** [comment]
fixed with https://github.com/thenextbilliononline/thenextbillion.online/pull/79 ! Will update the rest of the site style next
