### ISSUE TITLE
Resources Section

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#12]
Should include blog, wiki, and source code links.

**Comment by tati** [comment]
hmm so you are thinking we should have a third button here? Should it link to this repo then? @meyerscr 

![screen shot 2017-04-26 at 8 00 07 pm](https://cloud.githubusercontent.com/assets/12241872/25462130/027855ac-2abb-11e7-895d-0dc188a0c755.png)

**Comment by simplymathematics** [comment]
Yeah. We should move the Github button up there and make them all the same size.

**Comment by simplymathematics** [comment]
Also, we should keep a consistent theme with the iconography: 
![wiki-icon](https://cloud.githubusercontent.com/assets/15224968/25477236/7f7d4fbe-2b45-11e7-90ab-615920c0a31f.png) 

Blog icon? http://www.freeiconspng.com/uploads/lightbulb-icon-png-effects-17.png

**Comment by simplymathematics** [comment]
@tati The github should link to our org page, not the site repo: github.com/thenextbilliononline

**Comment by tati** [comment]
@meyerscr cool, I'm assuming you mean https://github.com/thenextbilliononline

**Comment by simplymathematics** [comment]
@tati We should have some copy between the links:
* Blog: We do case studies, weekend hacks, and discuss policy positions. Check here for our complete thoughts. 
* Wiki: Do you want to learn something? The wiki contains everything you need to know to code, build, and expand the internet. 
* Github: Do you like to hack? Do you like to code? Check out this neat collection of useful software (including this website and our wiki).

**Comment by tati** [comment]
should be fixed ish with https://github.com/thenextbilliononline/thenextbillion.online/pull/28
