### ISSUE TITLE
Email Address

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#22]
Set up mail forwarding on name.com

Set up mailgun for use inside of gmail

**Comment by simplymathematics** [comment]
https://simplyian.com/2015/01/07/Hacking-GMail-to-use-custom-domains-for-free/

**Comment by tati** [comment]
added DNS records, mailgun says wait a day / we may have to email mailgun...they are super annoying about disabled domains for no reason / I've dealt with them before

I got as far as logging into gmail stuff on [these instructions](https://simplyian.com/2015/01/07/Hacking-GMail-to-use-custom-domains-for-free/) but getting an error when I try to do that.

Also Mailgun still has the domain marked as "disabled" even tho all the DNS records are popping up as correct on the mailgun dashboard. I am gonna wait 24 hours and then email them if it's still not working

**Comment by simplymathematics** [comment]
It takes a day or two for the MX records to propagate across their network. I think it's a limitation thing, not them being difficult.
