### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#25]
- [x] Link to /blog from the front link
- [x] List blogs from most recent to oldest
- [x] Make new blog layout with the same format as meta layout, but has a different sidebar of blog archives
- [x] Automate the process as much as possible
- [x] Archives section

**Comment by simplymathematics** [comment]
http://prose.io/#thenextbilliononline/thenextbillion.online/blob/master

**Comment by meyerscr** [comment]
/blog not found. Maybe related to #45

**Comment by meyerscr** [comment]
Bulleted text needs to be larger.

**Comment by simplymathematics** [comment]
Displaying index of posts for /blog:
<ul>
  {% for post in site.posts %}
    <li>
      <a href="{{ post.url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

From: http://jekyllrb.com/docs/posts/
