### ISSUE TITLE
GAAAAAAAAAAAAAaH

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#38]
I broke it  
- [x] rename commits
- [x] push meta branch again

**Comment by tati** [comment]
@meyerscr can you confirm [this branch](https://github.com/thenextbilliononline/thenextbillion.online/tree/feature/clean-up) has everything / I didn't accidentally delete something? You can see commit history [here](https://github.com/thenextbilliononline/thenextbillion.online/commits/feature/clean-up).

**Comment by meyerscr** [comment]
I know that it takes some time for MX records to propagate across their servers. Chron jobs running once a day, probably.

**Comment by simplymathematics** [comment]
We're going to have to merge manually, but I cannot handle that myself. I changed the /meta and README sections last night pretty extensively. It also looks like your local branch was out of date by a couple days. In the future, can you just commit the files you've changed and not add --all? That will save us a lot of headache as we don't ever work on the same files.
