### ISSUE TITLE
Nav Bar Additions

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#4]
Include a 
* Blog
* Wiki

Or

Add the sections to the resources subsection as well as outside resources link as documented in the wiki

Get rid of the "Start Bootstrap"

**Comment by simplymathematics** [comment]
Wiki and blog will now go under the resources section

**Comment by tati** [comment]
ok minus the whole colors part (will deal with design stuff in another PR)...I think this will work, what do you think?

![screen shot 2017-04-26 at 7 45 26 pm](https://cloud.githubusercontent.com/assets/12241872/25461773/ee27c206-2ab8-11e7-91c8-d59809d8421a.png)

**Comment by tati** [comment]
fixed with https://github.com/thenextbilliononline/thenextbillion.online/pull/15
