### ISSUE TITLE
Copywriting 

### ISSUE THREAD

**Issue by Christianhendricks** [thenextbilliononline/thenextbillion.online#44]
@meyerscr 

In the opening copy block, it needs to be stated what "billion" you're talking about. a billion what? dollars? euros? humans? 

"industrialized places" should be something more like "developed countries" or "modernized regions;" the word 'industrialized' has baggage, and could technically refer to places where people are bussed in and out of industrial free trade zones without proper wages and thusly without technologies you're initially referring to.

**Comment by Christianhendricks** [comment]
"Technology solves the problems of rich, white people." <-- I get this, but there are non-white oligarchs in every country; white people weren't the ones censoring revolution in egypt, etc......

**Comment by simplymathematics** [comment]
Regarding the first comment, I believe your header solves that problem. 

I'll use the 1/2 the world  line in the About section below and replace the rich, white people line. Mention something about despots shutting down access...
