### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#5]
Use a new picture to build the new light blue/ grey theme

**Comment by tati** [comment]
🤔  better not sure if it's good enough yet tho...

![screen shot 2017-04-26 at 7 55 16 pm](https://cloud.githubusercontent.com/assets/12241872/25462035/5eb8f5ca-2aba-11e7-9064-acf145295a9b.png)

**Comment by tati** [comment]
v1 fix with https://github.com/thenextbilliononline/thenextbillion.online/pull/16
