### ISSUE TITLE
New HTML/CSS Edits 

### ISSUE THREAD

**Issue by Christianhendricks** [thenextbilliononline/thenextbillion.online#75]
Swap background image to this image: 

![background](https://cloud.githubusercontent.com/assets/21126726/25969637/a0cb52c8-3663-11e7-877e-8ab25d59c366.jpg)

---

changes to BODY css:

`background-color: #8a7b67
`
and 

`font-family: Montserrat,"Helvetica Neue",Helvetica,Arial,sans-serif
`
---
The top, main title text is an H1 tag. The H1 CSS style is currently set to: 

`    font-family: Montserrat,"Helvetica Neue",Helvetica,Arial,sans-serif;
`
Please change to: 

`    font-family: Lora, Times New Roman, serif;
`
----

Also in the title: Manually change the color of the last word ("ONLINE") to #ebb717. It should be done inline and probably look like this: 

```
<h1 class="brand-heading">The Next Billion 
<span style="color:#ebb717;">Online</span>
</h1>

```
---

Add floating icon logo to top left as fixed DIV. It should go as the very first line below `<!-- Navigation -->: `

`<div style="position:fixed;"> <img src="icon.png"> </div>
`
Image file here below (it's white and transparent, invisible here on white background, but it's there) : 

<img width="81" alt="icon" src="https://cloud.githubusercontent.com/assets/21126726/25969741/12fc16a2-3664-11e7-8c4a-6fbff585f0f4.png">

https://cloud.githubusercontent.com/assets/21126726/25969741/12fc16a2-3664-11e7-8c4a-6fbff585f0f4.png 

---

**Comment by meyerscr** [comment]
from @Christianhendricks 

so if you try to add this, you'll also need to Left-Align text and make it two side-by-side stackable DIVs for mobile.

**Comment by Christianhendricks** [comment]
I also sent charlie the GIF file if you want to try to add that. but if you try to add it, you'll also need to Left-Align text and make it two side-by-side stackable DIVs for mobile. 

Comp for what it would look like:

![d712b8a8-30d2-11e7-9dbf-06d5026cd5ec](https://cloud.githubusercontent.com/assets/21126726/25975572/1b01bb72-367d-11e7-8d1c-75dd50a995a1.gif)

**Comment by tati** [comment]
thanks @Christianhendricks all your stuff looks dope! I've updated the styling except new header structure, gonna open a separate issue for that

Fix with https://github.com/thenextbilliononline/thenextbillion.online/pull/82 and two PRs before that
