### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by simplymathematics** [thenextbilliononline/thenextbillion.online#8]
Need an icon.
* A satellite dish
* Or, we can use 10^9 (with the 9 rendered as a superscript) with wifi symbol?

**Comment by simplymathematics** [comment]
I'm leaning towards the 10^9, but open to other ideas.

**Comment by Christianhendricks** [comment]
Some rough drafts: 

![1](https://cloud.githubusercontent.com/assets/21126726/25681048/f1772560-3020-11e7-94fd-44b82388a5ef.jpg)
![2](https://cloud.githubusercontent.com/assets/21126726/25681049/f177738a-3020-11e7-9fe1-bc07ad6b2eda.jpg)
![3](https://cloud.githubusercontent.com/assets/21126726/25681050/f17f8a02-3020-11e7-8edf-c16bcb62dd9c.jpg)
![4](https://cloud.githubusercontent.com/assets/21126726/25681051/f1854564-3020-11e7-93c6-f07c118ba96b.jpg)

**Comment by simplymathematics** [comment]
Definitely not the 1st or 4th one as the lines obscure the meaning. Though, I could see a box working out. 

I vote for the second one!

**Comment by simplymathematics** [comment]
@tati what do you think?
