### ISSUE TITLE
New header

### ISSUE THREAD

**Issue by tati** [thenextbilliononline/thenextbillion.online#83]
![header](https://cloud.githubusercontent.com/assets/12241872/26030526/f59b98aa-3823-11e7-891c-7bc03d871914.gif)

**Comment by simplymathematics** [comment]
- [x] Include GIF
- [x] Replace scroll arrow with learn more section
- [x] Push centered text to right side and put ONLINE on its own line
- [x] tweak for mobile (use left half of image and re-align text?)

**Comment by brazilian-code** [comment]
GIF is in the _Includes/css/
